### ISSUE TITLE
 Request for Pre-trained Swin-L (1 dec layer) Model with COCO Outlier Supervision

### ISSUE THREAD

**Issue by xiaoran-roosevelt** [NazirNayal8/RbA#11]
![image](https://github.com/NazirNayal8/RbA/assets/48651387/74abed3a-01ef-46a1-ab32-b7ecc4ec48e0)
Hello,

I have been searching through your model zoo for the Swin-L (1 dec layer) model, specifically the version pre-trained only using the COCO dataset for Outlier Supervision, but it seems to be missing. I am wondering if this particular training setup was not conducted? If it has been, would it be possible for you to provide access to this model?

Thank you for your time and assistance, I look forward to your response!

**Comment by NazirNayal8** [comment]
Greetings @xiaoran-roosevelt ,

We have not conducted the experiment with swin-L (1 dec layer) using solely the COCO dataset but we have done it with COCO + Mapillary and you can find it in the MODEL ZOO in the repo. If you're interested in swin-L (1 dec layer) solely with COCO, we provide the weights of swin-L (1 dec layer) trained on cityscapes only in the MODEL ZOO which you can very easily finetune on COCO using the same config setup of swin-B which we also provide, it can be done on a single GPU and customized as much as needed with the config file. If you need more help on conducting this experiment let us know so that we can share more fine-grained details about it.

**Comment by xiaoran-roosevelt** [comment]
ok，i got it.Thank you very much!
